plugins {
    id 'com.android.application'
}

def releaseKeystorePath = System.getenv('ACEVO_KEYSTORE_PATH')
def releaseKeystorePassword = System.getenv('ACEVO_KEYSTORE_PASSWORD')

android {
    namespace 'com.greenbuddy.acevosetupengineer'
    compileSdk 36
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'com.greenbuddy.acevosetupengineer'
        minSdk 26
        targetSdk 36
        versionCode 23
        versionName '2.2.0'
    }

    signingConfigs {
        release {
            if (releaseKeystorePath != null && releaseKeystorePassword != null) {
                storeFile file(releaseKeystorePath)
                storePassword releaseKeystorePassword
                keyAlias 'acevosetup'
                keyPassword releaseKeystorePassword
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            if (releaseKeystorePath != null && releaseKeystorePassword != null) {
                signingConfig signingConfigs.release
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
