package com.greenbuddy.acevosetupengineer.engineering;

public enum HandlingIssue {
    REAR_NERVOUS,
    REAR_SLUGGISH,
    ENTRY_UNDERSTEER,
    MID_UNDERSTEER,
    EXIT_UNDERSTEER,
    ENTRY_OVERSTEER,
    MID_OVERSTEER,
    EXIT_OVERSTEER,
    BRAKING_INSTABILITY,
    POOR_TRACTION,
    BUMP_INSTABILITY,
    CURB_INSTABILITY,
    FRONT_TYRE_OVERHEAT,
    REAR_TYRE_OVERHEAT,
    STEERING_TOO_SHARP,
    STEERING_TOO_SLOW,
    DIRECT_REAR_WING_MORE,
    DIRECT_REAR_WING_LESS
}
