package com.greenbuddy.acevosetupengineer;

final class Catalog {
    static final String[] CARS = {
        "Abarth 695 Biposto (2022)",
        "Alfa Romeo 75 1.8 Turbo Evoluzione (1987)",
        "Alfa Romeo Giulia GTAm (2021)",
        "Alfa Romeo Junior Elettrica Veloce (2024)",
        "Alpine A110 S (2020)",
        "Alpine A290_β (2023)",
        "Audi RS 3 Sportback (2022)",
        "Audi Sport quattro (1983)",
        "Audi RS 6 Avant",
        "BMW M2 Coupe (G87)",
        "BMW M2 CS Racing (2020)",
        "BMW M3 E46 CSL (2003)",
        "BMW M3 Sport Evo (E30)",
        "BMW M4 CSL G82 (2022)",
        "BMW M4 GT3 EVO",
        "BMW M8 Competition (2022)",
        "Caterham 485 CSR",
        "Caterham Seven Academy Racer",
        "Chevrolet Camaro ZL1 (2022)",
        "Dallara EXP",
        "Dallara Stradale",
        "Ferrari 288 GTO",
        "Ferrari 296 GTB (2021)",
        "Ferrari 296 GT3",
        "Ferrari 488 Challenge Evo (2021)",
        "Ferrari Daytona SP3 (2021)",
        "Ferrari F40 LM (1993)",
        "Ferrari F2004",
        "Ferrari SF-25 (2025)",
        "Ford Escort RS Cosworth (1994)",
        "Ford Mustang GT3",
        "Honda NSX-R (1992)",
        "Honda S-2000 (2003)",
        "Hyundai i30 N Hatchback (2021)",
        "KTM X-BOW GT2",
        "KTM X-BOW GT4",
        "Lamborghini Countach",
        "Lamborghini Huracán STO (2021)",
        "Lamborghini Huracán Super Trofeo EVO2",
        "Lancia Delta HF Integrale Evoluzione 2 (1993)",
        "Lotus Emira (2021)",
        "Lotus Exige V6 Cup (2014)",
        "Maserati GT2 (2023)",
        "Mazda MX-5 NA (1994)",
        "Mazda MX5 ND Cup (2017)",
        "Mercedes-AMG GT2 (2023)",
        "Mercedes-Benz 190E AMG 2.5-16 Evo II",
        "Mini John Cooper S Mk VI (1990)",
        "Nissan Datsun 240Z (S30)",
        "Nissan Datsun 240Z (S30) – Tuned",
        "Peugeot 205 T16 (1984)",
        "Porsche 718 Cayman GT4 Clubsport",
        "Porsche 718 Cayman GT4 RS (2024)",
        "Porsche 911 (992) GT3 RS",
        "Porsche 991II GT2 RS Clubsport Evo",
        "Porsche 911 GT3 Cup [992] (2021)",
        "Porsche 911 Turbo 3.6 [964] (1993)",
        "Porsche 935",
        "Porsche 992 GT3 R Rennsport",
        "Renault 5 GT Turbo (1990)",
        "Toyota AE86",
        "Toyota AE86 Tuned",
        "Toyota GR86 (2024)",
        "Toyota Supra Turbo RZ (1998)",
        "Toyota Supra Turbo RZ V2 DRIFT",
        "Volkswagen Golf 8 GTI Clubsport (2022)",
        "Volkswagen Golf 8 R",
        "Volkswagen Golf GTI MK1",
        "Audi R8 LMS GT3 Evo II",
        "Audi R8 LMS GT4 Evo",
        "Alfa Romeo Giulia Sprint GTA (1965)"
    };

    static final String[] TRACKS = {
        "Bathurst", "Brands Hatch GP", "Brands Hatch Indy", "Circuit of the Americas",
        "Donington Park International", "Fuji Speedway", "Imola", "Kyalami Grand Prix",
        "Laguna Seca", "Monza", "Nürburgring GP", "Nürburgring Sprint",
        "Nürburgring 24h", "Nordschleife", "Nordschleife Touristenfahrten",
        "Oulton Park GP", "Oulton Park Fosters", "Paul Ricard", "Red Bull Ring",
        "Road Atlanta", "Sebring", "SPA Francorchamps", "Suzuka",
        "Watkins Glen Short Inner Loop"
    };

    private Catalog() {}
}
